name: trade_watch
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  fluttertoast: ^8.0.7
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.0.6
  provider: ^5.0.0
  images_picker: ^1.2.4
  intl: ^0.17.0
  google_sign_in: ^5.0.4
  firebase_core: ^1.2.1
  firebase_messaging: ^10.0.1
  flutter_local_notifications: ^6.0.0
  twitter_login: ^4.0.1
  dio: ^4.0.0
  country_code_picker: ^2.0.2
  http: ^0.13.3
  custom_check_box: ^0.0.3
  shared_preferences: ^2.0.6
  pin_code_fields: ^7.2.0
  fl_chart: ^0.36.2
  percent_indicator: ^3.0.1
  cloud_firestore: ^2.3.0
  flutter_webview_plugin: ^0.4.0
  jwt_decoder: ^2.0.1
  share: ^2.0.4
  flutter_login_facebook: ^1.0.1
  webview_flutter: ^2.0.9
  image_picker: ^0.8.2
  video_player: ^2.1.0
  youtube_player_flutter: ^8.0.0
  chewie: ^1.2.2
 # multi_image_picker: ^4.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - assets/images/
   - assets/icons/

  fonts:
    - family: pbl
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
    - family: pb
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: peb
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
    - family: pel
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
    - family: pl
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: pm
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: pr
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: psb
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: pt
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf